general {
    ignore_dbus_inhibit = false
}

# بعد 20 ثانية تقل الإضاءة بشكل قوي
listener {
    timeout = 20
    on-timeout = brightnessctl -s set 5%
    on-resume = brightnessctl -r
}

# بعد 40 ثانية تنطفئ تمامًا
listener {
    timeout = 40
    on-timeout = brightnessctl set 0%
    on-resume = brightnessctl -r
}

# بعد 10 دقائق يطفئ الجهاز
listener {
    timeout = 600
    on-timeout = systemctl poweroff
}