# ██╗      █████╗ ██╗   ██╗ ██████╗ ██╗   ██╗████████╗
# ██║     ██╔══██╗╚██╗ ██╔╝██╔═══██╗██║   ██║╚══██╔══╝
# ██║     ███████║ ╚████╔╝ ██║   ██║██║   ██║   ██║   
# ██║     ██╔══██║  ╚██╔╝  ██║   ██║██║   ██║   ██║   
# ███████╗██║  ██║   ██║   ╚██████╔╝╚██████╔╝   ██║   
# ╚══════╝╚═╝  ╚═╝   ╚═╝    ╚═════╝  ╚═════╝    ╚═╝   
#-----------------------------------------------------



dwindle {
    preserve_split = yes
}

master {
    new_status = master
}